### ISSUE TITLE
Collapse/expand pprint structure

### ISSUE THREAD

**Issue by ingesolvoll** [jpmonettas/flow-storm#11]
I don't know if this is trivial or not, but very large pprints aren't very useful in the tool, the long lines take time to process.

A presentation like the one in cljs-devtools would improve usability a lot.

**Comment by jpmonettas** [comment]
Yeah I have been thinking about that, but wasn't sure if a collapsable tree or a EQL filter is the tool for that.

https://github.com/jpmonettas/flow-storm-debugger/issues/4

**Comment by jpmonettas** [comment]
This is implemented now in flow-storm-debugger 0.3.5. See https://github.com/jpmonettas/flow-storm-debugger#exploring-expressions-results

**Comment by ingesolvoll** [comment]
Tested now, not sure if it's buggy or if I just don't understand. When tree icon is active, a String seems to be printed. Screenshot is from a re-frame event handler, so data printed should be a map, not a string.
![image](https://user-images.githubusercontent.com/426347/98740495-738e0880-23ab-11eb-9f76-f1099c1d135c.png)

**Comment by jpmonettas** [comment]
I think that is a bug for this case, because of the #reitit.core.Match object that doesn't deserialize in the debugger, since there is no reader tag for it, then it just shows a string. That is also why it isn't pprinting.

I'll think about those cases.

For a normal clojure datastructure (without reader tags) it should be working.

I'm reopening this issue to track this bug.

**Comment by jpmonettas** [comment]
Ok this should be fixed now in flow-storm-debugger 0.3.6! Please let me know if you find any issues with it.

**Comment by ingesolvoll** [comment]
@jpmonettas Confirming that it works. Thanks!
