### ISSUE TITLE
No tracing inside case

### ISSUE THREAD

**Issue by ingesolvoll** [jpmonettas/flow-storm#9]
Consider the following

```
(let [val :val1]
  (case val
    :val1 (if (= val :val2) "val1" "val3")
    :val2 "val2"))
```

The debugger will not step into the if statement, but jump directly to the value for the entire case.

**Comment by ingesolvoll** [comment]
Converted to a `cond`, it does step into the if:

```

(let [val :val1]
  (cond 
        (= val :val1) (if (= val :val2) "val1" "val3")
        (= val :val2) "val2"))
```

**Comment by jpmonettas** [comment]
Hmm weird, I'm not being able to reproduce

![flow-storm-issue-9](https://user-images.githubusercontent.com/786299/97699664-4bd4a180-1a89-11eb-9cd8-557fa6049350.gif)

Is it happening consistently with other case examples?

What versions of debugger/flow-storm are you testing with?

**Comment by ingesolvoll** [comment]
0.2.6 of debugger, 0.2.7 of flow-storm.

Do you need a video upload?

**Comment by ingesolvoll** [comment]
I'm on Clojure 1.9 and clojurescript 1.10.339, could that make a difference?

**Comment by ingesolvoll** [comment]
About other case examples, do you have any in mind that would be interesting cases? I did run into this on a few real production code examples, that's why I boiled it down to this minimal one.

**Comment by jpmonettas** [comment]
I was asking for more cases since I wasn't able to reproduce. 

Can you upload your flow file for this bug? Than maybe throws some light on it.

I'm currently focusing on a big release (both debugger and tracing lib) which includes a bunch of nice features and will move to polishing and bug fixing right after it.

**Comment by ingesolvoll** [comment]
Exciting stuff! Here's the file content

```
{:forms {75290450 "(let [val :val1]\n  (case val\n    :val1 (if (= val :val2) \"val1\" \"val3\")\n    :val2 \"val2\"))"}, :traces [{:flow-id 9523, :form-id 75290450, :form-flow-id 45316, :coor [], :timestamp 1604063637415} {:flow-id 9523, :form-id 75290450, :outer-form? nil, :coor [2 1], :result ":val1", :timestamp 1604063637418} {:flow-id 9523, :form-id 75290450, :outer-form? nil, :coor [2], :result "\"val3\"", :timestamp 1604063637419} {:flow-id 9523, :form-id 75290450, :outer-form? nil, :coor [], :result "\"val3\"", :timestamp 1604063637419} {:flow-id 9523, :form-id 75290450, :outer-form? true, :coor [], :result "\"val3\"", :timestamp 1604063637420}], :trace-idx 0, :bind-traces [{:flow-id 9523, :form-id 75290450, :coor [], :symbol "val", :value ":val1", :timestamp 1604063637417}], :flow-id 9523}
```

**Comment by ingesolvoll** [comment]
Already getting great value from the tools, as I've said before. I was just curious, what is your rationale for wanting to make a JavaFX version? Do you find it easier to make the things you want there?

**Comment by jpmonettas** [comment]
First thing is simplicity. 
Currently the tracer library sends traces to the debugger thru a web socket, because the UI runs on a different process (the browser) it needs to re send all those traces thru another websocket.

Same thing happens when working with the file system (or anything the browser isn't allowed to work with) I always end up with this pattern of having a unnecessary http server, sending messages back and forth using http (which also affects performance), and all that just because the UI runs in a different process.

I have a bunch of ideas I would like to explore for the debugger in the future and having the entire thing in the same jvm process is going to make everything much easier.

Does it make sense?

**Comment by ingesolvoll** [comment]
Certainly! And I see now that there is an issue on the debugger for this, I should have asked there.

The reason I asked is that intuitively I thought the developer experience in a webapp would be far superior to JavaFX for the one making it (you). But seems like you know what you are doing and are well on your way, looking forward to testing the new stuff :)

**Comment by jpmonettas** [comment]
The `case*` special form has different syntax in Clojure and ClojureScript. With that fix it should instrument the case body in both correctly.

**Comment by ingesolvoll** [comment]
Confirming that it works now, thanks!
